name: CI Pipeline
on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: ls -la ${{ github.workspace }}
#      - run: cd ${{ github.workspace }}
#      - run: make
