name: CI Pipeline
on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Compile ROM
        run: sudo make ci
